#pragma once

#define IDBITMAP_AO			101
#define IDBITMAP_DIFF		102
#define IDBITMAP_DISP		103
#define IDBITMAP_NOR		104
#define IDBITMAP_ROUGH		105
#define IDBITMAP_ROUGH_AO	106

#define IDBITMAP_ROCK_AO		201
#define IDBITMAP_ROCK_DIFF		202
#define IDBITMAP_ROCK_DISP		203
#define IDBITMAP_ROCK_NOR		204
#define IDBITMAP_ROCK_ROUGH		205
#define IDBITMAP_ROCK_ROUGH_AO	206

#define IDBITMAP_CBL_DIFF		302
#define IDBITMAP_CBL_DISP		303
#define IDBITMAP_CBL_NOR		304
#define IDBITMAP_CBL_ROUGH		305
